apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

configMapGenerator:
- name: capm3fasttrack-configmap
  literals:
  - CAPM3_FAST_TRACK=${CAPM3_FAST_TRACK:='false'}

generatorOptions:
  disableNameSuffixHash: true
