name: build-images-action

on:
  push:
    branches:
    - 'main'
    - 'release-*'
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build_CAPM3:
    name: Build CAPM3 image
    if: github.repository == 'metal3-io/cluster-api-provider-metal3'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'cluster-api-provider-metal3'
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
